models:
  - type: main
    model: gpt-3.5-turbo-instruct
    engine: openai
rails:
  output:
    flows:
      - self check output
    streaming:
      enabled: True
      chunk_size: 40
      context_size: 20
      stream_first: False

streaming: True
